<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Job_banner extends Model
{
    protected $fillable = ['market','title','image'];
    public function contents(){
        return $this->hasMany('App\Models\Banner_content','banner_id');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::deleted(function($model){
           $model->contents()->delete();
        });
    }
}
